name: publish-version

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy a new version of cyhole library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # set up environment
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r src/requirements.txt
      - name: install build
        run: python -m pip install --upgrade build

      # update library version equals release
      - name: update version in pyproject.toml
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          sed -i "s/{{PROJECT_VERSION}}/${TAG_NAME}/g" pyproject.toml

      # build package
      - name: build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      # publish on pypi
      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
